=== emmapapaioan/Fuel-Offers/xml/data_report.dtd
<!ELEMENT data_report (user_data, offers)>
<!ELEMENT user_data (name, vat, address, prefecture, municipality)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT vat (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT prefecture (#PCDATA)>
<!ELEMENT municipality (#PCDATA)>
<!ELEMENT offers (offer*)>
<!ELEMENT offer (fuel_type, expiring_date, price, active)>
<!ELEMENT fuel_type (#PCDATA)>
<!ELEMENT expiring_date (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT active (#PCDATA)>

=== emmapapaioan/Fuel-Offers/xml/data_report.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE data_report SYSTEM "xml/data_report.dtd">
<data_report>
  <user_data>
    <name>Μενέλαος Συνοδινός</name>
    <vat>123456656</vat>
    <address>Γούναρη 120</address>
    <prefecture>Αχαΐας</prefecture>
    <municipality>Πατρέων</municipality>
  </user_data>
  <offers>
    <offer>
      <fuel_type>Αμόλυβδη Βενζίνη 95</fuel_type>
      <expiring_date>2023-07-08</expiring_date>
      <price>2.00€</price>
      <active>True</active>
    </offer>
    <offer>
      <fuel_type>Αμόλυβδη Βενζίνη 98</fuel_type>
      <expiring_date>2023-06-10</expiring_date>
      <price>2.50€</price>
      <active>True</active>
    </offer>
    <offer>
      <fuel_type>Αμόλυβδη Βενζίνη 100</fuel_type>
      <expiring_date>2023-06-09</expiring_date>
      <price>3.00€</price>
      <active>True</active>
    </offer>
    <offer>
      <fuel_type>Πετρέλαιο Θέρμανσης</fuel_type>
      <expiring_date>2023-04-08</expiring_date>
      <price>2.00€</price>
      <active>False</active>
    </offer>
  </offers>
</data_report>
